upd flake and ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,6 +1,9 @@
 jobs:
   nixCI:
     name: Nix CI
+    permissions:
+      actions: write
+      contents: write
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout this repo
@@ -14,44 +17,55 @@ jobs:
             trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
             keep-outputs = true
       - name: Restore and cache Nix store
-        uses: deemp/cache-nix-too@v1
+        uses: nix-community/cache-nix-action@v1
         with:
-          key: nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
-          linux-gc-enabled: true
-          linux-max-store-size: 0
-          macos-gc-enabled: true
-          macos-max-store-size: 0
+          key: nix-${{ matrix.os }}-job-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
           restore-keys: |
-            nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
-            nix-${{ matrix.os }}-cachix-
+            nix-${{ matrix.os }}-job-
       - name: Remove old cache profiles
         run: rm -rf /nix/var/nix/profiles/cache
       - if: matrix.os == 'ubuntu-22.04'
-        name: Config git for github-actions
+        name: Configure git for github-actions
         run: |
           git config --global user.name github-actions
           git config --global user.email github-actions@github.com
       - if: matrix.os == 'ubuntu-22.04'
+        name: Format Nix files
+        run: |-
+          nix profile install .#format
+          nix run .#format
+      - if: matrix.os == 'ubuntu-22.04'
         name: Update flake locks
+        run: |-
+          nix profile install .#updateLocks
+          nix run .#updateLocks
+      - if: matrix.os == 'ubuntu-22.04'
+        name: Commit & Push
         run: |-
           git pull --rebase --autostash
 
-          nix profile install .#updateLocks
-          nix run .#updateLocks
+          git add .
 
-          git commit -a -m "action: Update flake locks" \
-                                 && git push || echo "push failed!"
+          git commit \
+            -m "action" \
+            -m "Format Nix files" \
+            -m "Update flake locks" \
+            || echo "commit failed!"
+
+          git push
       - name: Build package
+        run: nix profile install .#default
+      - name: Save flakes
         run: |-
-          nix build .#default
-          nix profile install .#default
-      - env:
-          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
-          CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
-        name: Push flakes to Cachix
-        run: |-
-          nix profile install .#pushToCachix
-          nix run .#pushToCachix
+          nix profile install .#saveFlakes
+          nix run .#saveFlakes
+      - name: Purge cache
+        uses: deemp/purge-cache@v1
+        with:
+          accessed: false
+          created: true
+          debug: true
+          max-age: 172800
     strategy:
       matrix:
         os:
